language: python
sudo: false
before_install: openssl version
env:
  global:
    - secure: AifoKzwhjV94cmcQZrdQmqRu/9rkZZvWpwBv1daeAQpLOKFPGsOm3D+x2cSw9+iCfkgDZDfqQVv1kCaFVxTll8v8jTq5SJdqEY0NmGWbj/UkNtShh609oRDsuzLxAEwtVKYjf/h8K2BRea+bl1tGkwZ2vtmYS6dxNlAijjWOfds=
    - secure: LBSEg/gMj4u4Hrpo3zs6Y/1mTpd2RtcN49mZIFgTdbJ9IhpiNPqcEt647Lz94F9Eses2x2WbNuKqZKZZReY7QLbEzU1m0nN5jlaKrjcG5NR5clNABfFFyhgc0jBikyS4abAG8jc2efeaTrFuQwdoF4sE8YiVrkiVj2X5Xoi6sBk=
  matrix:
    - TOX_SUFFIX="flakes"
    - TOX_SUFFIX="test"
matrix:
  exclude:
    - env: TOX_SUFFIX="flakes"
      python: 2.6
    - env: TOX_SUFFIX="flakes"
      python: 2.7
    - env: TOX_SUFFIX="flakes"
      python: 3.4
    - env: TOX_SUFFIX="flakes"
      python: 3.5
    - env: TOX_SUFFIX="flakes"
      python: pypy
    - env: TOX_SUFFIX="flakes"
      python: pypy3
python:
- 2.6
- 2.7
- 3.5
- 3.6
- pypy
- pypy3
install:
- pip install tox-travis
- if [[ $TOX_SUFFIX != 'flakes' ]]; then python setup.py install ; fi
script:
- tox -e "${TOX_SUFFIX}"
